# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pr:
 branches:
   include:
     - dev
     - main
   exclude:
     - test
 paths:
  exclude:
    - docs/*
    - README.md

trigger: 
 branches:
   include:
     - main
 paths:
   exclude:
     - docs/*
     - README.md
     - azure-pipelines.yaml
 


pool:
  vmImage: 'windows-2019'
variables:
  BuildConfiguration: release 

steps:
- task: DotNetCoreCLI@2
  inputs:
      command: 'restore'
      projects: '**/WebApp.csproj'
      feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*UnitTest*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Create Web App Package (.zip)
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact (WebApp.zip)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'  
